#!/usr/bin/env bash

set -euo pipefail
umask 022

die() {
    printf 'Error: %s\n' "$*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 ||
        die "Required command '$1' was not found."
}

for command_name in dpkg dpkg-deb file find gzip install patchelf; do
    require_command "${command_name}"
done

VERSION="${1:-0.1.0}"
ARCH="$(dpkg --print-architecture)"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKAGE_NAME="tintalle"
PACKAGE_ROOT="${PROJECT_ROOT}/build/deb/${PACKAGE_NAME}_${VERSION}_${ARCH}"
OUTPUT_DIR="${PROJECT_ROOT}/dist-packages"

PYINSTALLER_DIR="${PROJECT_ROOT}/dist/Tintalle"

APP_DIR="${PACKAGE_ROOT}/usr/lib/${PACKAGE_NAME}"
DOC_DIR="${PACKAGE_ROOT}/usr/share/doc/${PACKAGE_NAME}"
MAN_DIR="${PACKAGE_ROOT}/usr/share/man/man1"
LINTIAN_DIR="${PACKAGE_ROOT}/usr/share/lintian/overrides"

MAINTAINER_NAME="${DEBFULLNAME:-}"
MAINTAINER_EMAIL="${DEBEMAIL:-}"

if [[ -z "${MAINTAINER_NAME}" || -z "${MAINTAINER_EMAIL}" ]]; then
    die 'DEBFULLNAME and DEBEMAIL must be set. Example:
  export DEBFULLNAME="Your Name"
  export DEBEMAIL="email@example.com"'
fi

MAINTAINER="${MAINTAINER_NAME} <${MAINTAINER_EMAIL}>"

if [[ ! -x "${PYINSTALLER_DIR}/Tintalle" ]]; then
    printf '%s\n' \
        "Error: the PyInstaller executable was not found:" \
        "  ${PYINSTALLER_DIR}/Tintalle" \
        "" \
        "Build the Linux distribution first with:" \
        "  pyinstaller --clean --noconfirm tintalle-linux.spec" >&2
    exit 1
fi

required_files=(
    "${PROJECT_ROOT}/packaging/linux/tintalle"
    "${PROJECT_ROOT}/packaging/linux/io.github.jramboz.tintalle.desktop"
    "${PROJECT_ROOT}/packaging/linux/tintalle.1"
    "${PROJECT_ROOT}/packaging/linux/copyright"
    "${PROJECT_ROOT}/packaging/linux/lintian-overrides"
    "${PROJECT_ROOT}/img/tintalle.png"
    "${PROJECT_ROOT}/README.md"
)

for required_file in "${required_files[@]}"; do
    [[ -f "${required_file}" ]] ||
        die "Required file was not found: ${required_file}"
done

rm -rf "${PACKAGE_ROOT}"

mkdir -p \
    "${PACKAGE_ROOT}/DEBIAN" \
    "${APP_DIR}" \
    "${PACKAGE_ROOT}/usr/bin" \
    "${PACKAGE_ROOT}/usr/share/applications" \
    "${PACKAGE_ROOT}/usr/share/icons/hicolor/512x512/apps" \
    "${DOC_DIR}" \
    "${MAN_DIR}" \
    "${LINTIAN_DIR}" \
    "${OUTPUT_DIR}"

# Copy the complete distribution generated by PyInstaller.
cp -a \
    "${PYINSTALLER_DIR}/." \
    "${APP_DIR}/"

# Remove Windows-generated metadata files.
find "${APP_DIR}" \
    -type f \
    -iname "Thumbs.db" \
    -delete

# Remove private Pyenv paths while preserving any valid RUNPATH entries.
while IFS= read -r -d '' elf_file; do
    if ! file "${elf_file}" | grep -q "ELF"; then
        continue
    fi

    current_rpath="$(
        patchelf --print-rpath "${elf_file}" 2>/dev/null || true
    )"

    if [[ "${current_rpath}" != *"/.pyenv/"* ]]; then
        continue
    fi

    cleaned_rpath=""
    IFS=':' read -r -a rpath_entries <<< "${current_rpath}"

    for rpath_entry in "${rpath_entries[@]}"; do
        if [[ "${rpath_entry}" == *"/.pyenv/"* ]]; then
            continue
        fi

        if [[ -z "${cleaned_rpath}" ]]; then
            cleaned_rpath="${rpath_entry}"
        else
            cleaned_rpath+=":${rpath_entry}"
        fi
    done

    printf 'Removing private Pyenv RUNPATH from: %s\n' \
	"${elf_file#"${PACKAGE_ROOT}"/}"

    if [[ -n "${cleaned_rpath}" ]]; then
        patchelf --set-rpath "${cleaned_rpath}" "${elf_file}"
    else
        patchelf --remove-rpath "${elf_file}"
    fi
done < <(
    find "${APP_DIR}" \
        -type f \
        -print0
)

# Install the command-line launcher.
install -m 0755 \
    "${PROJECT_ROOT}/packaging/linux/tintalle" \
    "${PACKAGE_ROOT}/usr/bin/tintalle"

# Install the desktop application entry.
install -m 0644 \
    "${PROJECT_ROOT}/packaging/linux/io.github.jramboz.tintalle.desktop" \
    "${PACKAGE_ROOT}/usr/share/applications/io.github.jramboz.tintalle.desktop"

# Install the application icon.
install -m 0644 \
    "${PROJECT_ROOT}/img/tintalle.png" \
    "${PACKAGE_ROOT}/usr/share/icons/hicolor/512x512/apps/tintalle.png"

# Install the project documentation.
install -m 0644 \
    "${PROJECT_ROOT}/README.md" \
    "${DOC_DIR}/README"

# Install copyright and license information.
install -m 0644 \
    "${PROJECT_ROOT}/packaging/linux/copyright" \
    "${DOC_DIR}/copyright"

# Install the compressed manual page.
gzip -9n -c \
    "${PROJECT_ROOT}/packaging/linux/tintalle.1" \
    > "${MAN_DIR}/tintalle.1.gz"

chmod 0644 \
    "${MAN_DIR}/tintalle.1.gz"

# Generate the Debian package changelog.
cat > "${DOC_DIR}/changelog.Debian" <<EOF
tintalle (${VERSION}) unstable; urgency=medium

  * Initial Debian package for Linux.

 -- ${MAINTAINER}  $(LC_ALL=C date -R)
EOF

gzip -9n \
    "${DOC_DIR}/changelog.Debian"

# Install documented Lintian overrides for the PyInstaller bundle.
install -m 0644 \
    "${PROJECT_ROOT}/packaging/linux/lintian-overrides" \
    "${LINTIAN_DIR}/tintalle"

# Normalize package directory and file permissions.
find "${PACKAGE_ROOT}/usr" \
    -type d \
    -exec chmod 0755 {} +

find "${PACKAGE_ROOT}/usr" \
    -type f \
    -exec chmod 0644 {} +

# Restore executable permissions for ELF programs and scripts.
while IFS= read -r -d '' package_file; do
    file_type="$(file "${package_file}")"
    file_header="$(head -c 2 "${package_file}" 2>/dev/null || true)"

    if {
        [[ "${file_type}" == *"ELF"* ]] &&
        [[ "${file_type}" == *"executable"* ]]
    } || [[ "${file_header}" == "#!" ]]; then
        chmod 0755 "${package_file}"
    fi
done < <(
    find "${PACKAGE_ROOT}/usr" \
        -type f \
        -print0
)

# Explicitly ensure that the main launchers are executable.
chmod 0755 \
    "${PACKAGE_ROOT}/usr/bin/tintalle" \
    "${APP_DIR}/Tintalle"

# Calculate the final installed size after all package files are present.
INSTALLED_SIZE="$(du -sk "${PACKAGE_ROOT}/usr" | cut -f1)"

# Generate the Debian binary package metadata.
cat > "${PACKAGE_ROOT}/DEBIAN/control" <<EOF
Package: ${PACKAGE_NAME}
Version: ${VERSION}
Section: utils
Priority: optional
Architecture: ${ARCH}
Maintainer: ${MAINTAINER}
Homepage: https://github.com/jramboz/tintalle
Depends: libc6, libxcb-cursor0, libxcb-icccm4, libxcb-image0, libxcb-keysyms1, libxcb-render-util0
Installed-Size: ${INSTALLED_SIZE}
Description: graphical manager for OpenCore-based lightsabers
 Tintalle is a graphical application for managing compatible
 OpenCore-based lightsabers, including colors, sounds and files.
EOF

chmod 0644 \
    "${PACKAGE_ROOT}/DEBIAN/control"

# Build the package with root ownership for all installed files.
dpkg-deb \
    --root-owner-group \
    --build "${PACKAGE_ROOT}" \
    "${OUTPUT_DIR}/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"

printf '\nPackage generated:\n  %s\n' \
    "${OUTPUT_DIR}/${PACKAGE_NAME}_${VERSION}_${ARCH}.deb"
